steps:
  # Step 1: Installazione delle dipendenze
  - name: 'python'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  # Step 2: Deploy dell'app direttamente da codice sorgente
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'test-continuous-deployment',
           '--source', '.',
           '--region', 'europe-west3',  # Cambia regione se necessario
           '--platform', 'managed',
           '--allow-unauthenticated']

timeout: 1200s


